version: '3.8'

services:
  db:
    container_name: postgres_mccfg
    image: postgres:14.0-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}